pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps {
                deleteDir()
            }
        }
        stage("Stage 1"){
            steps {
                echo "This is Stage 1" 
            }
        }
        stage("Stage 2"){
            steps {
                echo "This is Stage 2"
            }
        }
    }
}
