pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo "Build number: ${env.BUILD_NUMBER}"
                // echo "Build number:"
                // sh "docker image build . -t ecr.com/websrver:${env.BUILD_NUMBER}"
            }
        }
    }
}